name: news_reader
description: A Flutter Project to Read Latest News.

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.1.0
  json_annotation: ^3.0.0
  cupertino_icons: ^0.1.2
  fluro: ^1.1.0
  flutter_webview_plugin: 
  timeago: ^1.2.0
  http: ^0.12.0+2
  rxdart: ^0.22.3  


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.7.1
  json_serializable: ^3.2.3
# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/news_reader_icon.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Nunito
    fonts:
    - asset: assets/fonts/Nunito-Bold.ttf
    - asset: assets/fonts/Nunito-Light.ttf
    - asset: assets/fonts/Nunito-LightItalic.ttf
    - asset: assets/fonts/Nunito-Regular.ttf
    - asset: assets/fonts/Nunito-SemiBold.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
